name: Build image of frontend

on:
  push:
    branches:
      - main

env:
  IMAGE_FRONTEND: audio-frontend

jobs:
  frontend-build:
    name: Build frontend image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: login into registry
        uses: docker/login-action@v3
        with:
          username: fabreantoine
          password: ${{ secrets.TOKEN_REGISTRY }}

      - name: find new version
        id: version-frontend
        run: |
          VERSION=$(grep '"version":' package.json | cut -d'"' -f4)
          if [ -z "$VERSION" ]; then
            echo "Failed to find version in package.json"
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: audio-frontend
          tags: |
            fabreantoine/${{ env.IMAGE_FRONTEND }}:${{ steps.version-frontend.outputs.version }}
            fabreantoine/${{ env.IMAGE_FRONTEND }}:latest
